In [0]:
from pyspark.sql.types import StructType, StructField, DoubleType, IntegerType

schema = StructType([
    StructField("engine_id", IntegerType(), True),
    StructField("cycle", IntegerType(), True),
    StructField("setting_1", DoubleType(), True),
    StructField("setting_2", DoubleType(), True),
    StructField("setting_3", DoubleType(), True)
] + [StructField(f"sensor_{i}", DoubleType(), True) for i in range(1, 22)])

In [0]:
spark.conf.set(
    "fs.azure.account.key.jana60305219.dfs.core.windows.net",
    "0GM7spdOovemizH7Y7FRNCvl/bLz5y0odTdC9mhp2Lm4/cxI9htWaDjHJU6iBEZlvhmmY8ymw3ic+AStT8nfqQ=="
)

In [0]:

storage_account = "jana60305219"
container = "raw"
file_path = f"abfss://{container}@{storage_account}.dfs.core.windows.net/train_FD001.txt"

df = spark.read.format("csv") \
    .option("sep", " ") \
    .schema(schema) \
    .load(file_path)

df.limit(10)

DataFrame[engine_id: int, cycle: int, setting_1: double, setting_2: double, setting_3: double, sensor_1: double, sensor_2: double, sensor_3: double, sensor_4: double, sensor_5: double, sensor_6: double, sensor_7: double, sensor_8: double, sensor_9: double, sensor_10: double, sensor_11: double, sensor_12: double, sensor_13: double, sensor_14: double, sensor_15: double, sensor_16: double, sensor_17: double, sensor_18: double, sensor_19: double, sensor_20: double, sensor_21: double]

In [0]:
pip install tsfresh scikit-learn matplotlib

Collecting tsfresh
  Downloading tsfresh-0.21.1-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: scikit-learn in /databricks/python3/lib/python3.12/site-packages (1.6.1)
Requirement already satisfied: matplotlib in /databricks/python3/lib/python3.12/site-packages (3.10.0)
Requirement already satisfied: requests>=2.9.1 in /databricks/python3/lib/python3.12/site-packages (from tsfresh) (2.32.3)
Requirement already satisfied: numpy>=1.15.1 in /databricks/python3/lib/python3.12/site-packages (from tsfresh) (2.1.3)
Requirement already satisfied: pandas>=0.25.0 in /databricks/python3/lib/python3.12/site-packages (from tsfresh) (2.2.3)
Requirement already satisfied: statsmodels>=0.13 in /databricks/python3/lib/python3.12/site-packages (from tsfresh) (0.14.4)
Requirement already satisfied: patsy>=0.4.1 in /databricks/python3/lib/python3.12/site-packages (from tsfresh) (1.0.1)
Collecting pywavelets (from tsfresh)
  Downloading pywavelets-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Collecting tqdm>=4.10.0 (from tsfresh)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting stumpy>=1.7.2 (from tsfresh)
  Downloading stumpy-1.14.1-py3-none-any.whl.metadata (28 kB)
Requirement already satisfied: cloudpickle in /databricks/python3/lib/python3.12/site-packages (from tsfresh) (3.0.0)
Requirement already satisfied: scipy>=1.14.0 in /databricks/python3/lib/python3.12/site-packages (from tsfresh) (1.15.1)
Requirement already satisfied: joblib>=1.2.0 in /databricks/python3/lib/python3.12/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /databricks/python3/lib/python3.12/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /databricks/python3/lib/python3.12/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /databricks/python3/lib/python3.12/site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /databricks/python3/lib/python3.12/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /databricks/python3/lib/python3.12/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /databricks/python3/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /databricks/python3/lib/python3.12/site-packages (from pandas>=0.25.0->tsfresh) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /databricks/python3/lib/python3.12/site-packages (from pandas>=0.25.0->tsfresh) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.9.1->tsfresh) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.9.1->tsfresh) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.9.1->tsfresh) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.9.1->tsfresh) (2025.1.31)
Collecting numba>=0.61.2 (from stumpy>=1.7.2->tsfresh)
  Downloading numba-0.64.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Collecting llvmlite<0.47,>=0.46.0dev0 (from numba>=0.61.2->stumpy>=1.7.2->tsfresh)
  Downloading llvmlite-0.46.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.0 kB)
Downloading tsfresh-0.21.1-py2.py3-none-any.whl (96 kB)
Downloading stumpy-1.14.1-py3-none-any.whl (183 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Downloading pywavelets-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 13.6 MB/s eta 0:00:00
Downloading numba-0.64.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 28.5 MB/s eta 0:00:00
Downloading llvmlite-0.46.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 28.1 MB/s eta 0:00:00
Installing collected packages: tqdm, pywavelets, llvmlite, numba, stumpy, tsfresh
Successfully installed llvmlite-0.46.0 numba-0.64.0 pywavelets-1.9.0 stumpy-1.14.1 tqdm-4.67.3 tsfresh-0.21.1
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
from pyspark.sql.types import StructType, StructField, DoubleType

def get_extraction_schema():
    return StructType([
        StructField("engine_id", IntegerType(), True)
    ])

In [0]:
import pandas as pd
from tsfresh import extract_features
from tsfresh.feature_extraction import EfficientFCParameters


pdf = df.toPandas()


features = extract_features(
    pdf,
    column_id="engine_id",
    column_sort="cycle",
    default_fc_parameters=EfficientFCParameters(),
    disable_progressbar=True
)

features.head()

   setting_1__variance_larger_than_standard_deviation  ...  sensor_21__mean_n_absolute_max__number_of_maxima_7
1                                                0.0   ...                                          23.479800
2                                                0.0   ...                                          23.536643
3                                                0.0   ...                                          23.484414
4                                                0.0   ...                                          23.458643
5                                                0.0   ...                                          23.524814

[5 rows x 18648 columns]

In [0]:
features = features.dropna(axis=1)

print(features.shape)

(100, 14953)

In [0]:
rul = pdf.groupby("engine_id")["cycle"].max()

rul.head()

engine_id
1    192
2    287
3    179
4    189
5    269
Name: cycle, dtype: int32

In [0]:
rul = rul.reset_index()
rul.rename(columns={"cycle": "RUL"}, inplace=True)

rul.head()

   engine_id  RUL
0          1  192
1          2  287
2          3  179
3          4  189
4          5  269

In [0]:
pdf = df.toPandas()
print(pdf.columns)

Index(['engine_id', 'cycle', 'setting_1', 'setting_2', 'setting_3', 'sensor_1',
       'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7',
       'sensor_8', 'sensor_9', 'sensor_10', 'sensor_11', 'sensor_12',
       'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17',
       'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21'],
      dtype='object')

In [0]:
pdf = df.toPandas()

pdf = pdf.dropna(axis=1)

print(pdf.columns)

Index(['engine_id', 'cycle', 'setting_1', 'setting_2', 'setting_3', 'sensor_1',
       'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7',
       'sensor_8', 'sensor_9', 'sensor_10', 'sensor_11', 'sensor_12',
       'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17',
       'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21'],
      dtype='object')

In [0]:
columns = ["engine_id","cycle","setting_1","setting_2","setting_3"] + [f"sensor_{i}" for i in range(1,22)]

pdf.columns = columns

pdf.head()

   engine_id  cycle  setting_1  ...  sensor_19  sensor_20  sensor_21
0          1      1    -0.0007  ...      100.0      39.06    23.4190
1          1      2     0.0019  ...      100.0      39.00    23.4236
2          1      3    -0.0043  ...      100.0      38.95    23.3442
3          1      4     0.0007  ...      100.0      38.88    23.3739
4          1      5    -0.0019  ...      100.0      38.90    23.4044

[5 rows x 26 columns]

In [0]:
print(features.index[:5])

Index([1, 2, 3, 4, 5], dtype='int32')

In [0]:
import pandas as pd
from tsfresh import extract_features
from tsfresh.feature_extraction import EfficientFCParameters

def distributed_tsfresh_extraction(pdf: pd.DataFrame) -> pd.DataFrame:
    
    extracted = extract_features(
        pdf, 
        column_id='engine_id', 
        column_sort='cycle',
        default_fc_parameters=EfficientFCParameters(),
        disable_progressbar=True
    )
    
  
    return extracted.reset_index().rename(columns={'index': 'engine_id'})

In [0]:
dataset = features.merge(rul, on="engine_id")

dataset.head()

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.ipykernel/2148/command-6523139935192310-3307210672 in ?()
----> 1 dataset = features.merge(rul, on="engine_id")
      2
      3 dataset.head()

/databricks/python/lib/python3.12/site-packages/pandas/core/frame.py in ?(self, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
  10828         validate: MergeValidate | None = None,
  10829     ) -> DataFrame:
  10830         from pandas.core.reshape.merge import merge
  10831
> 10832         return merge(
  10833             self,
  10834             right,
  10835             how=how,

/databricks/python/lib/python3.12/site-packages/pandas/core/reshape/merge.py in ?(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
    166             validate=validate,
    167             copy=copy,
    168         )
    169     else:
--> 170         op = _MergeOperation(
    171             left_df,
    172             right_df,
    173             how=how,

/databricks/python/lib/python3.12/site-packages/pandas/core/reshape/merge.py in ?(self, left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, indicator, validate)
    790             self.right_join_keys,
    791             self.join_names,
    792             left_drop,
    793             right_drop,
--> 794         ) = self._get_merge_keys()
    795
    796         if left_drop:
    797             self.left = self.left._drop_labels_or_levels(left_drop)

/databricks/python/lib/python3.12/site-packages/pandas/core/reshape/merge.py in ?(self)
   1306                     if lk is not None:
   1307                         # Then we're either Hashable or a wrong-length arraylike,
   1308                         #  the latter of which will raise
   1309                         lk = cast(Hashable, lk)
-> 1310                         left_keys.append(left._get_label_or_level_values(lk))
   1311                         join_names.append(lk)
   1312                     else:
   1313                         # work-around for merge_asof(left_index=True)

/databricks/python/lib/python3.12/site-packages/pandas/core/generic.py in ?(self, key, axis)
   1907             values = self.xs(key, axis=other_axes[0])._values
   1908         elif self._is_level_reference(key, axis=axis):
   1909             values = self.axes[axis].get_level_values(key)._values
   1910         else:
-> 1911             raise KeyError(key)
   1912
   1913         # Check for duplicates
   1914         if values.ndim > 1:

KeyError: 'engine_id'

In [0]:
X = dataset.drop(columns=["engine_id", "RUL"])
y = dataset["RUL"]